services:
services:
  backend:
    # In dev, mount source and run with reload enabled
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL
    ports:
      - "8000:8000"

  frontend:
    volumes:
      - ./frontend/src:/app/src
    command: npm run dev
    ports:
      - "3000:3000"
